# Generated by Django 3.0 on 2019-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0003_auto_20191211_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
