# Generated by Django 3.0 on 2019-12-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0004_auto_20191211_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='Enter your message', max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Enter your subject', max_length=50),
        ),
    ]
