# Generated by Django 3.0 on 2019-12-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0007_auto_20191212_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='Enter your message (max 300 chars)', max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Enter your subject (max 50 chars)', max_length=50),
        ),
    ]
