# Generated by Django 3.0 on 2019-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0009_auto_20191212_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=300, verbose_name='Max 300 chars'),
        ),
    ]
