# Generated by Django 3.0 on 2019-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0010_auto_20191212_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='Enter your message (max 300 chars)', max_length=300),
        ),
    ]
